### ISSUE TITLE
Add CI/CD with GitHub Actions

### ISSUE THREAD

**Issue by ibrahimadlani** [ibrahimadlani/lestanneriesfes#4]
### Feature Request: Add CI/CD with GitHub Actions

**Description:**
Implement Continuous Integration (CI) and Continuous Deployment (CD) for the Next.js project using GitHub Actions. The CI/CD pipeline should automatically run tests, ESLint, and Prettier on every pull request and merge to the `main` branch.

**Tasks:**
1. **Create GitHub Actions Workflow:**
   - Set up a GitHub Actions workflow file in `.github/workflows`.
   - Configure the workflow to trigger on pull requests and merges to the `main` branch.

2. **Install Dependencies:**
   - Ensure `jest`, `eslint`, and `prettier` are installed as dev dependencies.

3. **Configure Workflow Steps:**
   - **Checkout Code:** Use `actions/checkout` to check out the repository code.
   - **Setup Node.js:** Use `actions/setup-node` to set up Node.js environment.
   - **Install Dependencies:** Run `npm install` to install project dependencies.
   - **Run ESLint:** Execute `eslint` to lint the code.
   - **Run Prettier:** Execute `prettier --check` to check code formatting.
   - **Run Tests:** Execute `jest` to run unit tests.

**Example Workflow:**

```yaml
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier
      run: npm run prettier-check

    - name: Run Jest tests
      run: npm test
```
